services:
 # =======================
  # 🧩 MongoDB + Mongo Express
  # =======================
  mongodb:
    image: mongo
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wiwadev
      - MONGO_INITDB_ROOT_PASSWORD=wiwadev
    volumes:
      - mongo:/data
    networks:
      - microservices-net

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=wiwadev
      - ME_CONFIG_MONGODB_ADMINPASSWORD=wiwadev
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    networks:
      - microservices-net

  # =======================
  # 🦍 Kafka + Zookeeper
  # =======================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    container_name: ms_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-net

# =======================
# 🔗 Network + Volumes
# =======================
networks:
  microservices-net:
    driver: bridge

volumes:
  mongo:
